name: Build & Deploy Lambda

on: [push]

permissions:
  contents: write

jobs:
  Build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - uses: graalvm/setup-graalvm@v1
      with:
          java-version: '17'
          distribution: 'graalvm-community'
          github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup
      run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v1

    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/gradle-build-action@v2
      with:
        dependency-graph: generate-and-submit

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :app:buildNativeLambda --scan

    - name: Test with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: :app:test --scan
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Lambda
        path: app/build/libs

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: Lambda
          path: app/build/libs
      - uses: graalvm/setup-graalvm@v1
        with:
            java-version: '17'
            distribution: 'graalvm-community'
            github-token: ${{ secrets.GITHUB_TOKEN }}
    
      - name: Setup
        run: |
            echo "GRAALVM_HOME: $GRAALVM_HOME"
            echo "JAVA_HOME: $JAVA_HOME"
            java --version
            native-image --version
  
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
  
      - name: Setup Gradle to generate and submit dependency graphs
        uses: gradle/gradle-build-action@v2
        with:
          dependency-graph: generate-and-submit

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20
            
      - name: CDK Deploy
        env: # Or as an environment variable
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-2'
        run: |
            npm install -g aws-cdk
            cd infra 
            cdk diff
            cdk synth
            cdk deploy --require-approval never
      
