name: Build & Test Lambda

on: [push]

permissions:
  contents: write

jobs:
  Build:
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm-community'
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup
      run: |
        echo "GRAALVM_HOME: $GRAALVM_HOME"
        echo "JAVA_HOME: $JAVA_HOME"
        java --version
        native-image --version

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@v3

    - name: Setup Gradle to generate and submit dependency graphs
      uses: gradle/gradle-build-action@v3
      with:
        dependency-graph: generate-and-submit

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: :app:buildNativeLambda --scan

    - name: Test with Gradle
      uses: gradle/gradle-build-action@v3
      with:
        arguments: :app:test --scan
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Lambda
        path: app/build/libs
